### ISSUE TITLE
update JSON credentials after getting hacked

### ISSUE THREAD

**Issue by bbest** [BenioffOceanInitiative/ws-docker#2]
Need to create new JSON credentials after getting hacked. Here's where the credentials currently live:

* [Credentials – APIs & Services – Benioff Ocean Initi… – Google Cloud Platform](https://console.cloud.google.com/apis/credentials?authuser=3&project=benioff-ocean-initiative)
  ![image](https://user-images.githubusercontent.com/2837257/103031734-4046a980-4513-11eb-9bd9-45f239872cd4.png)

Here's a few more tips:

The name of the file in which the key is stored should not affect operations, so the quickest fix would be to simply update the contents of the existing JSON key files with the contents of the new key. We put the JSON keys in [gfw - Google Drive](https://drive.google.com/drive/u/3/folders/1crBGnOPGiKdWbtOLQhzgdJKA1ztZBzTM) since that's an easy password-protected place to share them. I don't remember using code that explicitly downloaded the contents of those keys for use in any scripts (since that would have to use the Google Drive API to authenticate).

To find all instances where a *.json file is read in for credentials, ie to replace contents of old key with new key, I again recommend revisiting every instance here:

[Search · org:BenioffOceanInitiative json](https://github.com/search?q=org%3ABenioffOceanInitiative+json&type=code) (see the 83 code results across BOI repos)

For instance, here's an example of defining a path to the old key stored as a JSON file and then its use in [ws-api: bq2pg.py#L20-L22](https://github.com/BenioffOceanInitiative/ws-api/blob/master/bq2pg.py#L20-L22):

```bash
credentials_json = '/home/admin/Benioff Ocean Initiative-454f666d1896.json'
# ...
credentials      = service_account.Credentials.from_service_account_file(credentials_json)
```

So the contents of the key file (*.json) are read in from outside the code stored in the Github repo. In this case it is on the server that runs the API, which I would normally access via [rstudio.whalesafe.com](https://rstudio.whalesafe.com). Then I could use the RStudio interface to update the credential contents to the latest in the existing file located at /home/admin/Benioff Ocean Initiative-454f666d1896.json (either through RStudio's File > Open... or Terminal and vi command).

You could update the filename while you're at it to maintain consistency. Just be sure to also update the code on the server and git commit and push those differences to the Github repo as well.

**Comment by bbest** [comment]
See also https://github.com/BenioffOceanInitiative/ws-api/issues/1

**Comment by bgaiarin** [comment]
1. Deleted old keys and re-activated SA **ships4whales@benioff-ocean-initiative.iam.gserviceaccount.com**. 
2. Created new key associated with SA **ships4whales@benioff-ocean-initiative.iam.gserviceaccount.com**. The ID of this new key is **34a5175767cfe66097c56ad30f2e46943f46bff4**.
2. Cut old key information and pasted new key information in **Benioff Ocean Initiative-454f666d1896.json** in gfw GDrive (https://drive.google.com/drive/u/1/folders/1crBGnOPGiKdWbtOLQhzgdJKA1ztZBzTM)
3. Cut old key information and pasted new key information in **Benioff Ocean Initiative-454f666d1896.json** in RStudio (rstudio.whalesafe.com) and saved.

**Comment by bbest** [comment]
Well done @bgaiarin! Almost closed in https://github.com/BenioffOceanInitiative/ws-api/issues/1#issuecomment-751313067
